import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "./globals.css";
import { App } from "@/app/_app";

const lexend = Lexend({ subsets: ["vietnamese"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={lexend.className}>
        <App>
          <div className="container flex min-h-screen flex-col justify-center gap-10">
            {children}
          </div>
        </App>
      </body>
    </html>
  );
}
